# Generated by Django 3.0.4 on 2020-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_pagarme', '0003_userpaymentprofile_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmeitemconfig',
            name='available_until',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Desativado em'),
        ),
    ]
