# Generated by Django 3.0.4 on 2020-10-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_pagarme', '0007_pagarmepayment_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('trialing', 'Experimentando'), ('pending_payment', 'Pagamento pendente'), ('unpaid', 'Inadimplente'), ('ended', 'Expirada'), ('canceled', 'Cancelada')], max_length=30)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='django_pagarme.Subscription')),
            ],
            options={
                'verbose_name': 'Notificação de Assinatura',
                'verbose_name_plural': 'Notificações de Assinatura',
                'ordering': ('-creation',),
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionnotification',
            index=models.Index(fields=['-creation', 'subscription'], name='notification_subscrip_creation'),
        ),
    ]
