# Generated by Django 3.0.4 on 2020-10-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_pagarme', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmepayment',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='django_pagarme.Subscription'),
        ),
    ]
